version: "3"
services: 
    node:
        build: .
        ports:
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        environment: 
            - PORT:${PORT}
        volumes: 
            - ./logs:/usr/app/logs:rw
            - ./src:/usr/app/src
    postgres:
        build: ./database
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}