version: "3"
services: 
    node:
        build: .
        ports:
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        environment: 
            - PORT:${PORT}
        volumes: 
            - ./logs:/usr/app/logs
            - ./src:/usr/app/src
        restart: always
        networks: 
            - rsnet
    postgres:
        build: ./database
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./postgresDB:/var/lib/postgresql/data:z
        networks: 
            - rsnet
networks:
    rsnet:
        external: true